fp = open('./ChineseCharacterTable.txt', "r")
string = fp.read()
fp.close()
string = string.replace(' ', '')
string = string.replace('\n', '')
string = string.replace('\t', '')
fp = open("./new2.txt", "w")
fp.write(string)
fp.close()
